version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    depends_on:
      - kafka
      - kafkahq
      - zookeeper
      - swagger

  swagger:
    image: swaggerapi/swagger-ui
    container_name: users-swagger
    restart: always
    environment:
      SWAGGER_JSON: /foo/swagger.yaml
    volumes:
      - ../api:/foo
    ports:
      - "3000:8080"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: debezium/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      ADVERTISED_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZOOKEEPER_CONNECT: zookeeper:2181
    container_name: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafkahq:
    image: tchiotludo/kafkahq
    container_name: kafkahq
    ports:
      - "8081:8080"
    environment:
      KAFKAHQ_CONFIGURATION: |
        kafkahq:
          connections:
            docker-kafka:
              properties:
                bootstrap.servers: "kafka:9092"
    depends_on:
      - kafka
